# Generated by Django 5.1.2 on 2025-12-01 06:10

import alumniapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0006_alumnipost_postcomment_follow_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_datetime', models.DateTimeField(validators=[alumniapp.models.validate_future_date])),
                ('file', models.FileField(upload_to='event_files/')),
            ],
        ),
    ]
