# Generated by Django 5.1.2 on 2025-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0008_gallery_alter_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnipost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to all alumni'), ('followers', 'Visible only to followers')], default='followers', max_length=20),
        ),
    ]
