# Generated by Django 5.1.2 on 2025-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0009_alumnipost_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='reset_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
