# Generated by Django 5.1.2 on 2025-12-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0010_registermodel_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donor_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fundraising_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
