# Generated by Django 5.1.2 on 2026-01-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0013_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='alumnipost',
            name='user',
        ),
        migrations.AddField(
            model_name='alumnipost',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnipost',
            name='alumni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='alumniapp.registermodel'),
        ),
        migrations.AlterField(
            model_name='alumnipost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alumnipost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to all'), ('followers', 'Visible only to followers')], default='followers', max_length=20),
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
