# Generated by Django 5.1.2 on 2026-01-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0014_alter_postlike_unique_together_remove_postlike_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='alumniapp.alumnipost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniapp.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='alumniapp.alumnipost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumniapp.registermodel')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
