# Generated by Django 5.1.2 on 2026-01-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0015_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='end_year',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AddField(
            model_name='student',
            name='start_year',
            field=models.PositiveIntegerField(default=2020),
        ),
    ]
