# Generated by Django 5.1.2 on 2026-01-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0016_student_end_year_student_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_year',
            field=models.PositiveIntegerField(),
        ),
    ]
