# Generated by Django 5.1.2 on 2026-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0017_alter_student_end_year_alter_student_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='null', max_length=10),
        ),
    ]
