# Generated by Django 5.1.2 on 2026-01-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0018_registermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], max_length=10),
        ),
    ]
