# Generated by Django 5.1.2 on 2026-01-16 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0019_alter_registermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='password',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long, contain at least one uppercase letter and one special character.', regex='^(?=.*[A-Z])(?=.*[^A-Za-z0-9]).{8,}$')]),
        ),
    ]
