# Generated by Django 5.1.2 on 2026-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0021_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('staff', 'Staff')], max_length=10),
        ),
    ]
