# Generated by Django 5.1.2 on 2026-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0024_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('post', 'Post'), ('job', 'Job'), ('follow', 'Follow')], max_length=10),
        ),
    ]
