# Generated by Django 6.0.2 on 2026-02-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniapp', '0026_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnipost',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='alumniapp.registermodel'),
        ),
    ]
